# Site
title:              Arahkun
bio:                'Arahkun Social Engineering Awareness Training & Information Security Education'
description:        "Arahkun Social Engineering Awareness Training & Information Security Education"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/bg_best.jpgg'
tiled_bg:           false   # 
locale:             en_US
url:                https://arahkun.github.io
# 
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
